#!/bin/sh
log() {
    echo "[sitepilot] $1"
}

generate() {
    SOURCE_FILE=$1
    DEST_FILE=$2
    
    cat $SOURCE_FILE | perl -p -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' > $DEST_FILE
}

log "Generating configuration files..."
mkdir -p /usr/local/lsws/conf/vhosts/app 
generate /conf/webserver/httpd_config.conf /usr/local/lsws/conf/httpd_config.conf
generate /conf/webserver/vhconf.conf /usr/local/lsws/conf/vhosts/app/vhconf.conf
generate /conf/webserver/sitepilot.ini /usr/local/lsws/lsphp72/etc/php/7.2/mods-available/00-sitepilot.ini

log "Updating user ID and GID..."
groupmod -g $WEBSERVER_USER_GID $WEBSERVER_USER_NAME
usermod -u $WEBSERVER_USER_ID $WEBSERVER_USER_NAME

log "Updating file permissions..."
chown -R $WEBSERVER_USER_NAME:$WEBSERVER_USER_NAME /var/www
chown -R $WEBSERVER_USER_NAME:$WEBSERVER_USER_NAME /tmp/lshttpd
chown -R lsadm:lsadm /usr/local/lsws/conf

# Start cronjobs
CRONFILE=/conf/crontabs/app
if test -f "$CRONFILE"; then
    log "Loading crontab ($CRONFILE)..."
    crontab $CRONFILE
fi

exec "$@"