#!/bin/sh
log() {
    echo "[sitepilot] $1"
}

generate() {
    SOURCE_FILE=$1
    DEST_FILE=$2
    
    cat $SOURCE_FILE | perl -p -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' > $DEST_FILE
}

log "Generating configuration files..."
generate /conf/nginx/nginx.conf /etc/nginx/nginx.conf 
generate /conf/nginx/default.conf /etc/nginx/conf.d/default.conf
generate /conf/php/www.conf /etc/php/$PHP_VER/php-fpm.d/www.conf

log "Updating user ID and GID..."
groupmod -g $WEBSERVER_USER_GID $WEBSERVER_USER_NAME
usermod -u $WEBSERVER_USER_ID $WEBSERVER_USER_NAME

log "Updating file permissions..."
chown -R $WEBSERVER_USER_NAME:$WEBSERVER_USER_NAME /var/www
chown -R $WEBSERVER_USER_NAME:$WEBSERVER_USER_NAME /var/tmp/nginx

# Start cronjobs
CRONFILE=/conf/crontabs/app
if test -f "$CRONFILE"; then
    log "Loading crontab ($CRONFILE)..."
    crontab $CRONFILE
fi

exec "$@"